# coding=utf-8
"""
colours.py - Colour definitions for the Python ldraw package.

Copyright (C) 2008 David Boddie <david@boddie.org.uk>
(C) 2020 Matthieu Berthomé <matthieu@mmea.fr>

This file is part of the ldraw Python package.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
<< Autogenerated source file >>
"""
# pylint: disable=invalid-name
from py4bricks.colour import Colour

Black = Colour(code=0, name="Black", rgb="#1B2A34", alpha=255, colour_attributes=[])
Blue = Colour(code=1, name="Blue", rgb="#1E5AA8", alpha=255, colour_attributes=[])
Green = Colour(code=2, name="Green", rgb="#00852B", alpha=255, colour_attributes=[])
Dark_Turquoise = Colour(code=3, name="Dark_Turquoise", rgb="#069D9F", alpha=255, colour_attributes=[])
Red = Colour(code=4, name="Red", rgb="#B40000", alpha=255, colour_attributes=[])
Dark_Pink = Colour(code=5, name="Dark_Pink", rgb="#D3359D", alpha=255, colour_attributes=[])
Brown = Colour(code=6, name="Brown", rgb="#543324", alpha=255, colour_attributes=[])
Light_Grey = Colour(code=7, name="Light_Grey", rgb="#8A928D", alpha=255, colour_attributes=[])
Dark_Grey = Colour(code=8, name="Dark_Grey", rgb="#545955", alpha=255, colour_attributes=[])
Light_Blue = Colour(code=9, name="Light_Blue", rgb="#97CBD9", alpha=255, colour_attributes=[])
Bright_Green = Colour(code=10, name="Bright_Green", rgb="#58AB41", alpha=255, colour_attributes=[])
Light_Turquoise = Colour(code=11, name="Light_Turquoise", rgb="#00AAA4", alpha=255, colour_attributes=[])
Salmon = Colour(code=12, name="Salmon", rgb="#F06D61", alpha=255, colour_attributes=[])
Pink = Colour(code=13, name="Pink", rgb="#F6A9BB", alpha=255, colour_attributes=[])
Yellow = Colour(code=14, name="Yellow", rgb="#FAC80A", alpha=255, colour_attributes=[])
White = Colour(code=15, name="White", rgb="#F4F4F4", alpha=255, colour_attributes=[])
Main_Colour = Colour(code=16, name="Main_Colour", rgb="#FFFF80", alpha=255, colour_attributes=[])
Light_Green = Colour(code=17, name="Light_Green", rgb="#ADD9A8", alpha=255, colour_attributes=[])
Light_Yellow = Colour(code=18, name="Light_Yellow", rgb="#FFD67F", alpha=255, colour_attributes=[])
Tan = Colour(code=19, name="Tan", rgb="#D7BA8C", alpha=255, colour_attributes=[])
Light_Violet = Colour(code=20, name="Light_Violet", rgb="#AFBED6", alpha=255, colour_attributes=[])
Glow_In_Dark_Opaque = Colour(code=21, name="Glow_In_Dark_Opaque", rgb="#E0FFB0", alpha=255, colour_attributes=[])
Purple = Colour(code=22, name="Purple", rgb="#671F81", alpha=255, colour_attributes=[])
Dark_Blue_Violet = Colour(code=23, name="Dark_Blue_Violet", rgb="#0E3E9A", alpha=255, colour_attributes=[])
Edge_Colour = Colour(code=24, name="Edge_Colour", rgb="#7F7F7F", alpha=255, colour_attributes=[])
Orange = Colour(code=25, name="Orange", rgb="#D67923", alpha=255, colour_attributes=[])
Magenta = Colour(code=26, name="Magenta", rgb="#901F76", alpha=255, colour_attributes=[])
Lime = Colour(code=27, name="Lime", rgb="#A5CA18", alpha=255, colour_attributes=[])
Dark_Tan = Colour(code=28, name="Dark_Tan", rgb="#897D62", alpha=255, colour_attributes=[])
Bright_Pink = Colour(code=29, name="Bright_Pink", rgb="#FF9ECD", alpha=255, colour_attributes=[])
Medium_Lavender = Colour(code=30, name="Medium_Lavender", rgb="#A06EB9", alpha=255, colour_attributes=[])
Lavender = Colour(code=31, name="Lavender", rgb="#CDA4DE", alpha=255, colour_attributes=[])
Trans_Black_Ir_Lens = Colour(code=32, name="Trans_Black_Ir_Lens", rgb="#000000", alpha=255, colour_attributes=[])
Trans_Dark_Blue = Colour(code=33, name="Trans_Dark_Blue", rgb="#0020A0", alpha=255, colour_attributes=[])
Trans_Green = Colour(code=34, name="Trans_Green", rgb="#237841", alpha=255, colour_attributes=[])
Trans_Bright_Green = Colour(code=35, name="Trans_Bright_Green", rgb="#56E646", alpha=255, colour_attributes=[])
Trans_Red = Colour(code=36, name="Trans_Red", rgb="#C91A09", alpha=255, colour_attributes=[])
Trans_Dark_Pink = Colour(code=37, name="Trans_Dark_Pink", rgb="#DF6695", alpha=255, colour_attributes=[])
Trans_Neon_Orange = Colour(code=38, name="Trans_Neon_Orange", rgb="#FF800D", alpha=255, colour_attributes=[])
Trans_Very_Light_Blue = Colour(code=39, name="Trans_Very_Light_Blue", rgb="#C1DFF0", alpha=255, colour_attributes=[])
Trans_Brown = Colour(code=40, name="Trans_Brown", rgb="#635F52", alpha=255, colour_attributes=[])
Trans_Medium_Blue = Colour(code=41, name="Trans_Medium_Blue", rgb="#559AB7", alpha=255, colour_attributes=[])
Trans_Neon_Green = Colour(code=42, name="Trans_Neon_Green", rgb="#C0FF00", alpha=255, colour_attributes=[])
Trans_Light_Blue = Colour(code=43, name="Trans_Light_Blue", rgb="#AEE9EF", alpha=255, colour_attributes=[])
Trans_Bright_Reddish_Lilac = Colour(code=44, name="Trans_Bright_Reddish_Lilac", rgb="#96709F", alpha=255, colour_attributes=[])
Trans_Pink = Colour(code=45, name="Trans_Pink", rgb="#FC97AC", alpha=255, colour_attributes=[])
Trans_Yellow = Colour(code=46, name="Trans_Yellow", rgb="#F5CD2F", alpha=255, colour_attributes=[])
Trans_Clear = Colour(code=47, name="Trans_Clear", rgb="#FCFCFC", alpha=255, colour_attributes=[])
Trans_Purple = Colour(code=52, name="Trans_Purple", rgb="#A5A5CB", alpha=255, colour_attributes=[])
Trans_Neon_Yellow = Colour(code=54, name="Trans_Neon_Yellow", rgb="#DAB000", alpha=255, colour_attributes=[])
Trans_Orange = Colour(code=57, name="Trans_Orange", rgb="#F08F1C", alpha=255, colour_attributes=[])
Chrome_Antique_Brass = Colour(code=60, name="Chrome_Antique_Brass", rgb="#645A4C", alpha=255, colour_attributes=['CHROME'])
Chrome_Blue = Colour(code=61, name="Chrome_Blue", rgb="#6C96BF", alpha=255, colour_attributes=['CHROME'])
Chrome_Green = Colour(code=62, name="Chrome_Green", rgb="#3CB371", alpha=255, colour_attributes=['CHROME'])
Chrome_Pink = Colour(code=63, name="Chrome_Pink", rgb="#AA4D8E", alpha=255, colour_attributes=['CHROME'])
Chrome_Black = Colour(code=64, name="Chrome_Black", rgb="#1B2A34", alpha=255, colour_attributes=['CHROME'])
Rubber_Yellow = Colour(code=65, name="Rubber_Yellow", rgb="#FAC80A", alpha=255, colour_attributes=['RUBBER'])
Rubber_Trans_Yellow = Colour(code=66, name="Rubber_Trans_Yellow", rgb="#F5CD2F", alpha=255, colour_attributes=['RUBBER'])
Rubber_Trans_Clear = Colour(code=67, name="Rubber_Trans_Clear", rgb="#FCFCFC", alpha=255, colour_attributes=['RUBBER'])
Very_Light_Orange = Colour(code=68, name="Very_Light_Orange", rgb="#FDC383", alpha=255, colour_attributes=[])
Bright_Reddish_Lilac = Colour(code=69, name="Bright_Reddish_Lilac", rgb="#8A12A8", alpha=255, colour_attributes=[])
Reddish_Brown = Colour(code=70, name="Reddish_Brown", rgb="#5F3109", alpha=255, colour_attributes=[])
Light_Bluish_Grey = Colour(code=71, name="Light_Bluish_Grey", rgb="#969696", alpha=255, colour_attributes=[])
Dark_Bluish_Grey = Colour(code=72, name="Dark_Bluish_Grey", rgb="#646464", alpha=255, colour_attributes=[])
Medium_Blue = Colour(code=73, name="Medium_Blue", rgb="#7396C8", alpha=255, colour_attributes=[])
Medium_Green = Colour(code=74, name="Medium_Green", rgb="#7FC475", alpha=255, colour_attributes=[])
Speckle_Black_Copper = Colour(code=75, name="Speckle_Black_Copper", rgb="#000000", alpha=255, colour_attributes=[])
Speckle_Dark_Bluish_Grey_Silver = Colour(code=76, name="Speckle_Dark_Bluish_Grey_Silver", rgb="#635F61", alpha=255, colour_attributes=[])
Light_Pink = Colour(code=77, name="Light_Pink", rgb="#FECCCF", alpha=255, colour_attributes=[])
Light_Nougat = Colour(code=78, name="Light_Nougat", rgb="#FFC995", alpha=255, colour_attributes=[])
Milky_White = Colour(code=79, name="Milky_White", rgb="#EEEEEE", alpha=255, colour_attributes=[])
Metallic_Silver = Colour(code=80, name="Metallic_Silver", rgb="#767676", alpha=255, colour_attributes=['METAL'])
Metallic_Green = Colour(code=81, name="Metallic_Green", rgb="#C2C06F", alpha=255, colour_attributes=['METAL'])
Metallic_Gold = Colour(code=82, name="Metallic_Gold", rgb="#DBAC34", alpha=255, colour_attributes=['METAL'])
Pearl_Black = Colour(code=83, name="Pearl_Black", rgb="#0A1327", alpha=255, colour_attributes=['PEARLESCENT'])
Medium_Nougat = Colour(code=84, name="Medium_Nougat", rgb="#AA7D55", alpha=255, colour_attributes=[])
Medium_Lilac = Colour(code=85, name="Medium_Lilac", rgb="#441A91", alpha=255, colour_attributes=[])
Light_Brown = Colour(code=86, name="Light_Brown", rgb="#7B5D41", alpha=255, colour_attributes=[])
Metallic_Dark_Grey = Colour(code=87, name="Metallic_Dark_Grey", rgb="#3E3C39", alpha=255, colour_attributes=['METAL'])
Blue_Violet = Colour(code=89, name="Blue_Violet", rgb="#1C58A7", alpha=255, colour_attributes=[])
Nougat = Colour(code=92, name="Nougat", rgb="#BB805A", alpha=255, colour_attributes=[])
Light_Salmon = Colour(code=100, name="Light_Salmon", rgb="#F9B7A5", alpha=255, colour_attributes=[])
Violet = Colour(code=110, name="Violet", rgb="#26469A", alpha=255, colour_attributes=[])
Medium_Violet = Colour(code=112, name="Medium_Violet", rgb="#4861AC", alpha=255, colour_attributes=[])
Glitter_Trans_Dark_Pink = Colour(code=114, name="Glitter_Trans_Dark_Pink", rgb="#DF6695", alpha=255, colour_attributes=[])
Medium_Lime = Colour(code=115, name="Medium_Lime", rgb="#B7D425", alpha=255, colour_attributes=[])
Glitter_Trans_Clear = Colour(code=117, name="Glitter_Trans_Clear", rgb="#EEEEEE", alpha=255, colour_attributes=[])
Aqua = Colour(code=118, name="Aqua", rgb="#9CD6CC", alpha=255, colour_attributes=[])
Light_Lime = Colour(code=120, name="Light_Lime", rgb="#DEEA92", alpha=255, colour_attributes=[])
Light_Orange = Colour(code=121, name="Light_Orange", rgb="#F89A39", alpha=255, colour_attributes=[])
Dark_Salmon = Colour(code=123, name="Dark_Salmon", rgb="#EE5434", alpha=255, colour_attributes=[])
Spud_Orange = Colour(code=125, name="Spud_Orange", rgb="#F9A777", alpha=255, colour_attributes=[])
Dark_Nougat = Colour(code=128, name="Dark_Nougat", rgb="#AD6140", alpha=255, colour_attributes=[])
Glitter_Trans_Purple = Colour(code=129, name="Glitter_Trans_Purple", rgb="#640061", alpha=255, colour_attributes=[])
Speckle_Black_Silver = Colour(code=132, name="Speckle_Black_Silver", rgb="#000000", alpha=255, colour_attributes=[])
Speckle_Black_Gold = Colour(code=133, name="Speckle_Black_Gold", rgb="#000000", alpha=255, colour_attributes=[])
Copper = Colour(code=134, name="Copper", rgb="#764D3B", alpha=255, colour_attributes=['PEARLESCENT'])
Pearl_Light_Grey = Colour(code=135, name="Pearl_Light_Grey", rgb="#A0A0A0", alpha=255, colour_attributes=['PEARLESCENT'])
Metallic_Blue = Colour(code=137, name="Metallic_Blue", rgb="#5B7590", alpha=255, colour_attributes=['PEARLESCENT'])
Pearl_Light_Gold = Colour(code=142, name="Pearl_Light_Gold", rgb="#DEAC66", alpha=255, colour_attributes=['PEARLESCENT'])
Pearl_Dark_Gold = Colour(code=147, name="Pearl_Dark_Gold", rgb="#83724F", alpha=255, colour_attributes=['PEARLESCENT'])
Pearl_Dark_Grey = Colour(code=148, name="Pearl_Dark_Grey", rgb="#484D48", alpha=255, colour_attributes=['PEARLESCENT'])
Pearl_Very_Light_Grey = Colour(code=150, name="Pearl_Very_Light_Grey", rgb="#989B99", alpha=255, colour_attributes=['PEARLESCENT'])
Very_Light_Bluish_Grey = Colour(code=151, name="Very_Light_Bluish_Grey", rgb="#C8C8C8", alpha=255, colour_attributes=[])
Trans_Neon_Red = Colour(code=158, name="Trans_Neon_Red", rgb="#F18EBB", alpha=255, colour_attributes=[])
Pearl_Red = Colour(code=176, name="Pearl_Red", rgb="#945148", alpha=255, colour_attributes=['PEARLESCENT'])
Pearl_Yellow = Colour(code=178, name="Pearl_Yellow", rgb="#AB673A", alpha=255, colour_attributes=['PEARLESCENT'])
Pearl_Silver = Colour(code=179, name="Pearl_Silver", rgb="#898788", alpha=255, colour_attributes=['PEARLESCENT'])
Dark_Yellow = Colour(code=180, name="Dark_Yellow", rgb="#DD982E", alpha=255, colour_attributes=[])
Pearl_White = Colour(code=183, name="Pearl_White", rgb="#F6F2DF", alpha=255, colour_attributes=['PEARLESCENT'])
Metallic_Bright_Red = Colour(code=184, name="Metallic_Bright_Red", rgb="#D60026", alpha=255, colour_attributes=['PEARLESCENT'])
Metallic_Bright_Blue = Colour(code=185, name="Metallic_Bright_Blue", rgb="#0059A3", alpha=255, colour_attributes=['PEARLESCENT'])
Metallic_Dark_Green = Colour(code=186, name="Metallic_Dark_Green", rgb="#008E3C", alpha=255, colour_attributes=['PEARLESCENT'])
Pearl_Brown = Colour(code=187, name="Pearl_Brown", rgb="#57392C", alpha=255, colour_attributes=['PEARLESCENT'])
Reddish_Gold = Colour(code=189, name="Reddish_Gold", rgb="#AC8247", alpha=255, colour_attributes=['PEARLESCENT'])
Bright_Light_Orange = Colour(code=191, name="Bright_Light_Orange", rgb="#FCAC00", alpha=255, colour_attributes=[])
Lemon_Metallic = Colour(code=200, name="Lemon_Metallic", rgb="#708224", alpha=255, colour_attributes=['PEARLESCENT'])
Bright_Light_Blue = Colour(code=212, name="Bright_Light_Blue", rgb="#9DC3F7", alpha=255, colour_attributes=[])
Medium_Blue_Violet = Colour(code=213, name="Medium_Blue_Violet", rgb="#476FB6", alpha=255, colour_attributes=[])
Rust = Colour(code=216, name="Rust", rgb="#872B17", alpha=255, colour_attributes=[])
Reddish_Lilac = Colour(code=218, name="Reddish_Lilac", rgb="#8E5597", alpha=255, colour_attributes=[])
Lilac = Colour(code=219, name="Lilac", rgb="#564E9D", alpha=255, colour_attributes=[])
Light_Lilac = Colour(code=220, name="Light_Lilac", rgb="#9195CA", alpha=255, colour_attributes=[])
Warm_Yellowish_Orange = Colour(code=225, name="Warm_Yellowish_Orange", rgb="#FAA964", alpha=255, colour_attributes=[])
Bright_Light_Yellow = Colour(code=226, name="Bright_Light_Yellow", rgb="#FFEC6C", alpha=255, colour_attributes=[])
Trans_Bright_Light_Green = Colour(code=227, name="Trans_Bright_Light_Green", rgb="#B5D96C", alpha=255, colour_attributes=[])
Trans_Bright_Light_Orange = Colour(code=231, name="Trans_Bright_Light_Orange", rgb="#FCB76D", alpha=255, colour_attributes=[])
Sky_Blue = Colour(code=232, name="Sky_Blue", rgb="#77C9D8", alpha=255, colour_attributes=[])
Trans_Fire_Yellow = Colour(code=234, name="Trans_Fire_Yellow", rgb="#FBE890", alpha=255, colour_attributes=[])
Rubber_Black = Colour(code=256, name="Rubber_Black", rgb="#1B2A34", alpha=255, colour_attributes=['RUBBER'])
Dark_Blue = Colour(code=272, name="Dark_Blue", rgb="#19325A", alpha=255, colour_attributes=[])
Rubber_Blue = Colour(code=273, name="Rubber_Blue", rgb="#1E5AA8", alpha=255, colour_attributes=['RUBBER'])
Trans_Reddish_Lilac = Colour(code=284, name="Trans_Reddish_Lilac", rgb="#C281A5", alpha=255, colour_attributes=[])
Trans_Light_Green = Colour(code=285, name="Trans_Light_Green", rgb="#7DC291", alpha=255, colour_attributes=[])
Dark_Green = Colour(code=288, name="Dark_Green", rgb="#00451A", alpha=255, colour_attributes=[])
Trans_Light_Blue_Violet = Colour(code=293, name="Trans_Light_Blue_Violet", rgb="#6BABE4", alpha=255, colour_attributes=[])
Glow_In_Dark_Trans = Colour(code=294, name="Glow_In_Dark_Trans", rgb="#BDC6AD", alpha=255, colour_attributes=[])
Flamingo_Pink = Colour(code=295, name="Flamingo_Pink", rgb="#FF94C2", alpha=255, colour_attributes=[])
Cool_Silver = Colour(code=296, name="Cool_Silver", rgb="#ADADAD", alpha=255, colour_attributes=['PEARLESCENT'])
Pearl_Gold = Colour(code=297, name="Pearl_Gold", rgb="#AA7F2E", alpha=255, colour_attributes=['PEARLESCENT'])
Metallic_Copper = Colour(code=300, name="Metallic_Copper", rgb="#C27F53", alpha=255, colour_attributes=['METAL'])
Glitter_Trans_Light_Blue = Colour(code=302, name="Glitter_Trans_Light_Blue", rgb="#AEE9EF", alpha=255, colour_attributes=[])
Dark_Brown = Colour(code=308, name="Dark_Brown", rgb="#352100", alpha=255, colour_attributes=[])
Maersk_Blue = Colour(code=313, name="Maersk_Blue", rgb="#ABD9FF", alpha=255, colour_attributes=[])
Flat_Silver = Colour(code=315, name="Flat_Silver", rgb="#8C8C8C", alpha=255, colour_attributes=['PEARLESCENT'])
Titanium_Metallic = Colour(code=316, name="Titanium_Metallic", rgb="#3E3C39", alpha=255, colour_attributes=['PEARLESCENT'])
Dark_Red = Colour(code=320, name="Dark_Red", rgb="#720012", alpha=255, colour_attributes=[])
Dark_Azure = Colour(code=321, name="Dark_Azure", rgb="#469BC3", alpha=255, colour_attributes=[])
Medium_Azure = Colour(code=322, name="Medium_Azure", rgb="#68C3E2", alpha=255, colour_attributes=[])
Light_Aqua = Colour(code=323, name="Light_Aqua", rgb="#D3F2EA", alpha=255, colour_attributes=[])
Rubber_Red = Colour(code=324, name="Rubber_Red", rgb="#B40000", alpha=255, colour_attributes=['RUBBER'])
Yellowish_Green = Colour(code=326, name="Yellowish_Green", rgb="#E2F99A", alpha=255, colour_attributes=[])
Glow_In_Dark_White = Colour(code=329, name="Glow_In_Dark_White", rgb="#F5F3D7", alpha=255, colour_attributes=[])
Olive_Green = Colour(code=330, name="Olive_Green", rgb="#77774E", alpha=255, colour_attributes=[])
Fluorescent_Red_Ink = Colour(code=332, name="Fluorescent_Red_Ink", rgb="#D06D4F", alpha=255, colour_attributes=[])
Fluorescent_Green_Ink = Colour(code=333, name="Fluorescent_Green_Ink", rgb="#DBEA7A", alpha=255, colour_attributes=[])
Chrome_Gold = Colour(code=334, name="Chrome_Gold", rgb="#DFC176", alpha=255, colour_attributes=['CHROME'])
Sand_Red = Colour(code=335, name="Sand_Red", rgb="#88605E", alpha=255, colour_attributes=[])
Glitter_Trans_Neon_Green = Colour(code=339, name="Glitter_Trans_Neon_Green", rgb="#C0FF00", alpha=255, colour_attributes=[])
Glitter_Trans_Orange = Colour(code=341, name="Glitter_Trans_Orange", rgb="#F08F1C", alpha=255, colour_attributes=[])
Conductive_Black = Colour(code=342, name="Conductive_Black", rgb="#3E3C39", alpha=255, colour_attributes=['PEARLESCENT'])
Reddish_Copper = Colour(code=346, name="Reddish_Copper", rgb="#803D07", alpha=255, colour_attributes=['PEARLESCENT'])
Rubber_Orange = Colour(code=350, name="Rubber_Orange", rgb="#D67923", alpha=255, colour_attributes=['RUBBER'])
Medium_Dark_Pink = Colour(code=351, name="Medium_Dark_Pink", rgb="#F785B1", alpha=255, colour_attributes=[])
Coral = Colour(code=353, name="Coral", rgb="#FF6D77", alpha=255, colour_attributes=[])
Opal_Trans_Clear = Colour(code=360, name="Opal_Trans_Clear", rgb="#FCFCFC", alpha=255, colour_attributes=[])
Opal_Trans_Light_Blue = Colour(code=362, name="Opal_Trans_Light_Blue", rgb="#AEE9EF", alpha=255, colour_attributes=[])
Opal_Trans_Black = Colour(code=363, name="Opal_Trans_Black", rgb="#635F52", alpha=255, colour_attributes=[])
Opal_Trans_Dark_Pink = Colour(code=364, name="Opal_Trans_Dark_Pink", rgb="#DF6695", alpha=255, colour_attributes=[])
Opal_Trans_Purple = Colour(code=365, name="Opal_Trans_Purple", rgb="#671F81", alpha=255, colour_attributes=[])
Earth_Orange = Colour(code=366, name="Earth_Orange", rgb="#D86D2C", alpha=255, colour_attributes=[])
Opal_Trans_Green = Colour(code=367, name="Opal_Trans_Green", rgb="#237841", alpha=255, colour_attributes=[])
Neon_Yellow = Colour(code=368, name="Neon_Yellow", rgb="#EDFF21", alpha=255, colour_attributes=[])
Medium_Brown = Colour(code=370, name="Medium_Brown", rgb="#755945", alpha=255, colour_attributes=[])
Medium_Tan = Colour(code=371, name="Medium_Tan", rgb="#CCA373", alpha=255, colour_attributes=[])
Sand_Purple = Colour(code=373, name="Sand_Purple", rgb="#75657D", alpha=255, colour_attributes=[])
Rubber_Light_Grey = Colour(code=375, name="Rubber_Light_Grey", rgb="#8A928D", alpha=255, colour_attributes=['RUBBER'])
Opal_Trans_Yellow = Colour(code=376, name="Opal_Trans_Yellow", rgb="#F5CD2F", alpha=255, colour_attributes=[])
Sand_Green = Colour(code=378, name="Sand_Green", rgb="#708E7C", alpha=255, colour_attributes=[])
Sand_Blue = Colour(code=379, name="Sand_Blue", rgb="#70819A", alpha=255, colour_attributes=[])
Chrome_Silver = Colour(code=383, name="Chrome_Silver", rgb="#CECECE", alpha=255, colour_attributes=['CHROME'])
Reddish_Orange = Colour(code=402, name="Reddish_Orange", rgb="#CA4C0B", alpha=255, colour_attributes=[])
Rubber_Dark_Blue = Colour(code=406, name="Rubber_Dark_Blue", rgb="#19325A", alpha=255, colour_attributes=['RUBBER'])
Sienna_Brown = Colour(code=422, name="Sienna_Brown", rgb="#915C3C", alpha=255, colour_attributes=[])
Umber_Brown = Colour(code=423, name="Umber_Brown", rgb="#543F33", alpha=255, colour_attributes=[])
Ochre_Yellow = Colour(code=424, name="Ochre_Yellow", rgb="#DD9E47", alpha=255, colour_attributes=[])
Warm_Pink = Colour(code=430, name="Warm_Pink", rgb="#F79B9B", alpha=255, colour_attributes=[])
Bright_Blue_Violet = Colour(code=431, name="Bright_Blue_Violet", rgb="#665EA7", alpha=255, colour_attributes=[])
Rubber_Purple = Colour(code=449, name="Rubber_Purple", rgb="#671F81", alpha=255, colour_attributes=['RUBBER'])
Fabuland_Brown = Colour(code=450, name="Fabuland_Brown", rgb="#D27744", alpha=255, colour_attributes=[])
Medium_Orange = Colour(code=462, name="Medium_Orange", rgb="#F58624", alpha=255, colour_attributes=[])
Dark_Orange = Colour(code=484, name="Dark_Orange", rgb="#91501C", alpha=255, colour_attributes=[])
Rubber_Lime = Colour(code=490, name="Rubber_Lime", rgb="#A5CA18", alpha=255, colour_attributes=['RUBBER'])
Magnet = Colour(code=493, name="Magnet", rgb="#656761", alpha=255, colour_attributes=['METAL'])
Electric_Contact_Alloy = Colour(code=494, name="Electric_Contact_Alloy", rgb="#D0D0D0", alpha=255, colour_attributes=['METAL'])
Electric_Contact_Copper = Colour(code=495, name="Electric_Contact_Copper", rgb="#AE7A59", alpha=255, colour_attributes=['METAL'])
Rubber_Light_Bluish_Grey = Colour(code=496, name="Rubber_Light_Bluish_Grey", rgb="#969696", alpha=255, colour_attributes=['RUBBER'])
Very_Light_Grey = Colour(code=503, name="Very_Light_Grey", rgb="#BCB4A5", alpha=255, colour_attributes=[])
Rubber_Flat_Silver = Colour(code=504, name="Rubber_Flat_Silver", rgb="#898788", alpha=255, colour_attributes=['RUBBER'])
Obsolete_Light_Orange_Brown = Colour(code=507, name="Obsolete_Light_Orange_Brown", rgb="#FA9C1C", alpha=255, colour_attributes=[])
Fabuland_Red = Colour(code=508, name="Fabuland_Red", rgb="#C65127", alpha=255, colour_attributes=[])
Fabuland_Orange = Colour(code=509, name="Fabuland_Orange", rgb="#CF8A47", alpha=255, colour_attributes=[])
Fabuland_Lime = Colour(code=510, name="Fabuland_Lime", rgb="#ACE35A", alpha=255, colour_attributes=[])
Rubber_White = Colour(code=511, name="Rubber_White", rgb="#F4F4F4", alpha=255, colour_attributes=['RUBBER'])
Rubber_Green = Colour(code=10002, name="Rubber_Green", rgb="#00852B", alpha=255, colour_attributes=['RUBBER'])
Rubber_Dark_Turquoise = Colour(code=10003, name="Rubber_Dark_Turquoise", rgb="#069D9F", alpha=255, colour_attributes=['RUBBER'])
Rubber_Dark_Pink = Colour(code=10005, name="Rubber_Dark_Pink", rgb="#D3359D", alpha=255, colour_attributes=['RUBBER'])
Rubber_Dark_Grey = Colour(code=10008, name="Rubber_Dark_Grey", rgb="#545955", alpha=255, colour_attributes=['RUBBER'])
Rubber_Bright_Green = Colour(code=10010, name="Rubber_Bright_Green", rgb="#58AB41", alpha=255, colour_attributes=['RUBBER'])
Lemon = Colour(code=10015, name="Lemon", rgb="#FFF230", alpha=255, colour_attributes=[])
Rose_Pink = Colour(code=10017, name="Rose_Pink", rgb="#FF9494", alpha=255, colour_attributes=[])
Rubber_Tan = Colour(code=10019, name="Rubber_Tan", rgb="#D7BA8C", alpha=255, colour_attributes=['RUBBER'])
Yellowish_Dark_Pink = Colour(code=10022, name="Yellowish_Dark_Pink", rgb="#D05098", alpha=255, colour_attributes=[])
Rubber_Magenta = Colour(code=10026, name="Rubber_Magenta", rgb="#901F76", alpha=255, colour_attributes=['RUBBER'])
Rubber_Dark_Tan = Colour(code=10028, name="Rubber_Dark_Tan", rgb="#897D62", alpha=255, colour_attributes=['RUBBER'])
Rubber_Bright_Pink = Colour(code=10029, name="Rubber_Bright_Pink", rgb="#FF9ECD", alpha=255, colour_attributes=['RUBBER'])
Rubber_Medium_Lavender = Colour(code=10030, name="Rubber_Medium_Lavender", rgb="#A06EB9", alpha=255, colour_attributes=['RUBBER'])
Rubber_Lavender = Colour(code=10031, name="Rubber_Lavender", rgb="#CDA4DE", alpha=255, colour_attributes=['RUBBER'])
Rubber_Trans_Bright_Green = Colour(code=10035, name="Rubber_Trans_Bright_Green", rgb="#56E646", alpha=255, colour_attributes=['RUBBER'])
Rubber_Trans_Red = Colour(code=10036, name="Rubber_Trans_Red", rgb="#C91A09", alpha=255, colour_attributes=['RUBBER'])
Rubber_Trans_Light_Blue = Colour(code=10043, name="Rubber_Trans_Light_Blue", rgb="#AEE9EF", alpha=255, colour_attributes=['RUBBER'])
Metallic_Light_Blue = Colour(code=10045, name="Metallic_Light_Blue", rgb="#97CBD9", alpha=255, colour_attributes=['METAL'])
Metallic_Pink = Colour(code=10046, name="Metallic_Pink", rgb="#AD659A", alpha=255, colour_attributes=['METAL'])
Trans_Sticker = Colour(code=10047, name="Trans_Sticker", rgb="#FFFFFF", alpha=255, colour_attributes=[])
Metallic_Light_Pink = Colour(code=10049, name="Metallic_Light_Pink", rgb="#FECCCF", alpha=255, colour_attributes=['METAL'])
Rubber_Trans_Orange = Colour(code=10057, name="Rubber_Trans_Orange", rgb="#F08F1C", alpha=255, colour_attributes=['RUBBER'])
Rubber_Reddish_Brown = Colour(code=10070, name="Rubber_Reddish_Brown", rgb="#5F3109", alpha=255, colour_attributes=['RUBBER'])
Rubber_Dark_Bluish_Grey = Colour(code=10072, name="Rubber_Dark_Bluish_Grey", rgb="#646464", alpha=255, colour_attributes=['RUBBER'])
Rubber_Medium_Blue = Colour(code=10073, name="Rubber_Medium_Blue", rgb="#7396C8", alpha=255, colour_attributes=['RUBBER'])
Rubber_Light_Nougat = Colour(code=10078, name="Rubber_Light_Nougat", rgb="#FFC995", alpha=255, colour_attributes=['RUBBER'])
Rubber_Milky_White = Colour(code=10079, name="Rubber_Milky_White", rgb="#EEEEEE", alpha=255, colour_attributes=['RUBBER'])
Rubber_Medium_Nougat = Colour(code=10084, name="Rubber_Medium_Nougat", rgb="#AA7D55", alpha=255, colour_attributes=['RUBBER'])
Rubber_Medium_Lilac = Colour(code=10085, name="Rubber_Medium_Lilac", rgb="#441A91", alpha=255, colour_attributes=['RUBBER'])
Rubber_Nougat = Colour(code=10092, name="Rubber_Nougat", rgb="#BB805A", alpha=255, colour_attributes=['RUBBER'])
Rubber_Pearl_Light_Grey = Colour(code=10135, name="Rubber_Pearl_Light_Grey", rgb="#A0A0A0", alpha=255, colour_attributes=['RUBBER'])
Rubber_Metallic_Blue = Colour(code=10137, name="Rubber_Metallic_Blue", rgb="#5B7590", alpha=255, colour_attributes=['RUBBER'])
Rubber_Pearl_Dark_Gold = Colour(code=10147, name="Rubber_Pearl_Dark_Gold", rgb="#83724F", alpha=255, colour_attributes=['RUBBER'])
Rubber_Pearl_Dark_Grey = Colour(code=10148, name="Rubber_Pearl_Dark_Grey", rgb="#484D48", alpha=255, colour_attributes=['RUBBER'])
Rubber_Pearl_Very_Light_Grey = Colour(code=10150, name="Rubber_Pearl_Very_Light_Grey", rgb="#989B99", alpha=255, colour_attributes=['RUBBER'])
Rubber_Very_Light_Bluish_Grey = Colour(code=10151, name="Rubber_Very_Light_Bluish_Grey", rgb="#C8C8C8", alpha=255, colour_attributes=['RUBBER'])
Rubber_Reddish_Gold = Colour(code=10189, name="Rubber_Reddish_Gold", rgb="#AC8247", alpha=255, colour_attributes=['RUBBER'])
Rubber_Bright_Light_Orange = Colour(code=10191, name="Rubber_Bright_Light_Orange", rgb="#FCAC00", alpha=255, colour_attributes=['RUBBER'])
Rubber_Lemon_Metallic = Colour(code=10200, name="Rubber_Lemon_Metallic", rgb="#708224", alpha=255, colour_attributes=['RUBBER'])
Rubber_Bright_Light_Blue = Colour(code=10212, name="Rubber_Bright_Light_Blue", rgb="#9DC3F7", alpha=255, colour_attributes=['RUBBER'])
Rubber_Bright_Light_Yellow = Colour(code=10226, name="Rubber_Bright_Light_Yellow", rgb="#FFEC6C", alpha=255, colour_attributes=['RUBBER'])
Rubber_Dark_Green = Colour(code=10288, name="Rubber_Dark_Green", rgb="#00451A", alpha=255, colour_attributes=['RUBBER'])
Rubber_Pearl_Gold = Colour(code=10297, name="Rubber_Pearl_Gold", rgb="#AA7F2E", alpha=255, colour_attributes=['RUBBER'])
Rubber_Dark_Brown = Colour(code=10308, name="Rubber_Dark_Brown", rgb="#352100", alpha=255, colour_attributes=['RUBBER'])
Rubber_Dark_Red = Colour(code=10320, name="Rubber_Dark_Red", rgb="#720012", alpha=255, colour_attributes=['RUBBER'])
Rubber_Dark_Azure = Colour(code=10321, name="Rubber_Dark_Azure", rgb="#469BC3", alpha=255, colour_attributes=['RUBBER'])
Rubber_Medium_Azure = Colour(code=10322, name="Rubber_Medium_Azure", rgb="#68C3E2", alpha=255, colour_attributes=['RUBBER'])
Rubber_Light_Aqua = Colour(code=10323, name="Rubber_Light_Aqua", rgb="#D3F2EA", alpha=255, colour_attributes=['RUBBER'])
Rubber_Yellowish_Green = Colour(code=10326, name="Rubber_Yellowish_Green", rgb="#E2F99A", alpha=255, colour_attributes=['RUBBER'])
Rubber_Olive_Green = Colour(code=10330, name="Rubber_Olive_Green", rgb="#77774E", alpha=255, colour_attributes=['RUBBER'])
Glitter_Trans_Bright_Green = Colour(code=10351, name="Glitter_Trans_Bright_Green", rgb="#56E646", alpha=255, colour_attributes=[])
Opal_Trans_Dark_Blue = Colour(code=10366, name="Opal_Trans_Dark_Blue", rgb="#0020A0", alpha=255, colour_attributes=[])
Trans_Black = Colour(code=10375, name="Trans_Black", rgb="#212121", alpha=255, colour_attributes=[])
Rubber_Sand_Green = Colour(code=10378, name="Rubber_Sand_Green", rgb="#708E7C", alpha=255, colour_attributes=['RUBBER'])
Rubber_Dark_Orange = Colour(code=10484, name="Rubber_Dark_Orange", rgb="#91501C", alpha=255, colour_attributes=['RUBBER'])
Trans_White = Colour(code=11015, name="Trans_White", rgb="#F4F4F4", alpha=255, colour_attributes=[])
Trans_Tan = Colour(code=11019, name="Trans_Tan", rgb="#D7BA8C", alpha=255, colour_attributes=[])
Canvas_Black = Colour(code=20000, name="Canvas_Black", rgb="#1B2A34", alpha=255, colour_attributes=[])
Canvas_Blue = Colour(code=20001, name="Canvas_Blue", rgb="#1E5AA8", alpha=255, colour_attributes=[])
Canvas_Green = Colour(code=20002, name="Canvas_Green", rgb="#00852B", alpha=255, colour_attributes=[])
Canvas_Red = Colour(code=20004, name="Canvas_Red", rgb="#B40000", alpha=255, colour_attributes=[])
Canvas_Brown = Colour(code=20006, name="Canvas_Brown", rgb="#543324", alpha=255, colour_attributes=[])
Canvas_Light_Grey = Colour(code=20007, name="Canvas_Light_Grey", rgb="#8A928D", alpha=255, colour_attributes=[])
Canvas_Bright_Green = Colour(code=20010, name="Canvas_Bright_Green", rgb="#58AB41", alpha=255, colour_attributes=[])
Canvas_Yellow = Colour(code=20014, name="Canvas_Yellow", rgb="#FAC80A", alpha=255, colour_attributes=[])
Canvas_White = Colour(code=20015, name="Canvas_White", rgb="#F4F4F4", alpha=255, colour_attributes=[])
Canvas_Tan = Colour(code=20019, name="Canvas_Tan", rgb="#D7BA8C", alpha=255, colour_attributes=[])
Canvas_Purple = Colour(code=20022, name="Canvas_Purple", rgb="#671F81", alpha=255, colour_attributes=[])
Canvas_Dark_Tan = Colour(code=20028, name="Canvas_Dark_Tan", rgb="#897D62", alpha=255, colour_attributes=[])
Canvas_Reddish_Brown = Colour(code=20070, name="Canvas_Reddish_Brown", rgb="#5F3109", alpha=255, colour_attributes=[])
Canvas_Light_Bluish_Grey = Colour(code=20071, name="Canvas_Light_Bluish_Grey", rgb="#969696", alpha=255, colour_attributes=[])
Canvas_Dark_Bluish_Grey = Colour(code=20072, name="Canvas_Dark_Bluish_Grey", rgb="#646464", alpha=255, colour_attributes=[])
Canvas_Light_Brown = Colour(code=20086, name="Canvas_Light_Brown", rgb="#7B5D41", alpha=255, colour_attributes=[])
Canvas_Dark_Green = Colour(code=20288, name="Canvas_Dark_Green", rgb="#00451A", alpha=255, colour_attributes=[])
Canvas_Dark_Red = Colour(code=20320, name="Canvas_Dark_Red", rgb="#720012", alpha=255, colour_attributes=[])
Canvas_Sand_Red = Colour(code=20335, name="Canvas_Sand_Red", rgb="#88605E", alpha=255, colour_attributes=[])
Canvas_Cream = Colour(code=20500, name="Canvas_Cream", rgb="#F8F3E4", alpha=255, colour_attributes=[])
Modulex_Clear = Colour(code=30000, name="Modulex_Clear", rgb="#FCFCFC", alpha=255, colour_attributes=[])
Modulex_White = Colour(code=30001, name="Modulex_White", rgb="#F4F4F4", alpha=255, colour_attributes=[])
Modulex_Light_Grey = Colour(code=30002, name="Modulex_Light_Grey", rgb="#8A928D", alpha=255, colour_attributes=[])
Modulex_Black = Colour(code=30003, name="Modulex_Black", rgb="#34434D", alpha=255, colour_attributes=[])
Modulex_Terracotta = Colour(code=30004, name="Modulex_Terracotta", rgb="#D27744", alpha=255, colour_attributes=[])
Modulex_Buff = Colour(code=30005, name="Modulex_Buff", rgb="#D7BA8C", alpha=255, colour_attributes=[])
Modulex_Ochre_Yellow = Colour(code=30006, name="Modulex_Ochre_Yellow", rgb="#FED557", alpha=255, colour_attributes=[])
Modulex_Olive_Green = Colour(code=30007, name="Modulex_Olive_Green", rgb="#7C9051", alpha=255, colour_attributes=[])
Modulex_Teal_Blue = Colour(code=30008, name="Modulex_Teal_Blue", rgb="#467083", alpha=255, colour_attributes=[])
Modulex_Brown = Colour(code=30009, name="Modulex_Brown", rgb="#907450", alpha=255, colour_attributes=[])
Modulex_Strong_Red = Colour(code=30010, name="Modulex_Strong_Red", rgb="#B40000", alpha=255, colour_attributes=[])
Modulex_Pastel_Blue = Colour(code=30011, name="Modulex_Pastel_Blue", rgb="#ABD9FF", alpha=255, colour_attributes=[])
Modulex_Orange = Colour(code=30012, name="Modulex_Orange", rgb="#D86D2C", alpha=255, colour_attributes=[])
Modulex_Red = Colour(code=30013, name="Modulex_Red", rgb="#C65127", alpha=255, colour_attributes=[])
Modulex_Pastel_Green = Colour(code=30014, name="Modulex_Pastel_Green", rgb="#78FC78", alpha=255, colour_attributes=[])
Modulex_Lemon = Colour(code=30015, name="Modulex_Lemon", rgb="#FFF230", alpha=255, colour_attributes=[])
Modulex_Pink = Colour(code=30016, name="Modulex_Pink", rgb="#F785B1", alpha=255, colour_attributes=[])
Modulex_Light_Bluish_Grey = Colour(code=30032, name="Modulex_Light_Bluish_Grey", rgb="#AFB5C7", alpha=255, colour_attributes=[])
Modulex_Pink_Red = Colour(code=30033, name="Modulex_Pink_Red", rgb="#F45C40", alpha=255, colour_attributes=[])
Modulex_Aqua_Green = Colour(code=30034, name="Modulex_Aqua_Green", rgb="#27867E", alpha=255, colour_attributes=[])
Modulex_Light_Yellow = Colour(code=30035, name="Modulex_Light_Yellow", rgb="#FFE371", alpha=255, colour_attributes=[])
Modulex_Violet = Colour(code=30037, name="Modulex_Violet", rgb="#BD7D85", alpha=255, colour_attributes=[])
Modulex_Medium_Blue = Colour(code=30038, name="Modulex_Medium_Blue", rgb="#61AFFF", alpha=255, colour_attributes=[])
Modulex_Light_Orange = Colour(code=30039, name="Modulex_Light_Orange", rgb="#F7AD63", alpha=255, colour_attributes=[])
Modulex_Charcoal_Grey = Colour(code=30040, name="Modulex_Charcoal_Grey", rgb="#595D60", alpha=255, colour_attributes=[])
Modulex_Dark_Brown = Colour(code=30054, name="Modulex_Dark_Brown", rgb="#330000", alpha=255, colour_attributes=[])
Modulex_Foil_White = Colour(code=30080, name="Modulex_Foil_White", rgb="#F4F4F4", alpha=255, colour_attributes=[])
Modulex_Foil_Black = Colour(code=30081, name="Modulex_Foil_Black", rgb="#34434D", alpha=255, colour_attributes=[])
Modulex_Foil_Dark_Grey = Colour(code=30082, name="Modulex_Foil_Dark_Grey", rgb="#595D60", alpha=255, colour_attributes=[])
Modulex_Foil_Light_Grey = Colour(code=30083, name="Modulex_Foil_Light_Grey", rgb="#9C9C9C", alpha=255, colour_attributes=[])
Modulex_Foil_Dark_Green = Colour(code=30084, name="Modulex_Foil_Dark_Green", rgb="#006400", alpha=255, colour_attributes=[])
Modulex_Foil_Light_Green = Colour(code=30085, name="Modulex_Foil_Light_Green", rgb="#7DB538", alpha=255, colour_attributes=[])
Modulex_Foil_Dark_Blue = Colour(code=30086, name="Modulex_Foil_Dark_Blue", rgb="#0057A6", alpha=255, colour_attributes=[])
Modulex_Foil_Light_Blue = Colour(code=30087, name="Modulex_Foil_Light_Blue", rgb="#68AECE", alpha=255, colour_attributes=[])
Modulex_Foil_Violet = Colour(code=30088, name="Modulex_Foil_Violet", rgb="#4B0082", alpha=255, colour_attributes=[])
Modulex_Foil_Dark_Red = Colour(code=30089, name="Modulex_Foil_Dark_Red", rgb="#8B0000", alpha=255, colour_attributes=[])
Modulex_Foil_Yellow = Colour(code=30090, name="Modulex_Foil_Yellow", rgb="#FED557", alpha=255, colour_attributes=[])
Modulex_Foil_Orange = Colour(code=30091, name="Modulex_Foil_Orange", rgb="#F7AD63", alpha=255, colour_attributes=[])
Modulex_Dark_Grey = Colour(code=31000, name="Modulex_Dark_Grey", rgb="#6B5A5A", alpha=255, colour_attributes=[])
Modulex_Blue = Colour(code=31001, name="Modulex_Blue", rgb="#0057A6", alpha=255, colour_attributes=[])
Modulex_Very_Light_Grey = Colour(code=31002, name="Modulex_Very_Light_Grey", rgb="#D9D5CC", alpha=255, colour_attributes=[])

ColoursByCode = {
    0: Black,
    1: Blue,
    2: Green,
    3: Dark_Turquoise,
    4: Red,
    5: Dark_Pink,
    6: Brown,
    7: Light_Grey,
    8: Dark_Grey,
    9: Light_Blue,
    10: Bright_Green,
    11: Light_Turquoise,
    12: Salmon,
    13: Pink,
    14: Yellow,
    15: White,
    16: Main_Colour,
    17: Light_Green,
    18: Light_Yellow,
    19: Tan,
    20: Light_Violet,
    21: Glow_In_Dark_Opaque,
    22: Purple,
    23: Dark_Blue_Violet,
    24: Edge_Colour,
    25: Orange,
    26: Magenta,
    27: Lime,
    28: Dark_Tan,
    29: Bright_Pink,
    30: Medium_Lavender,
    31: Lavender,
    32: Trans_Black_Ir_Lens,
    33: Trans_Dark_Blue,
    34: Trans_Green,
    35: Trans_Bright_Green,
    36: Trans_Red,
    37: Trans_Dark_Pink,
    38: Trans_Neon_Orange,
    39: Trans_Very_Light_Blue,
    40: Trans_Brown,
    41: Trans_Medium_Blue,
    42: Trans_Neon_Green,
    43: Trans_Light_Blue,
    44: Trans_Bright_Reddish_Lilac,
    45: Trans_Pink,
    46: Trans_Yellow,
    47: Trans_Clear,
    52: Trans_Purple,
    54: Trans_Neon_Yellow,
    57: Trans_Orange,
    60: Chrome_Antique_Brass,
    61: Chrome_Blue,
    62: Chrome_Green,
    63: Chrome_Pink,
    64: Chrome_Black,
    65: Rubber_Yellow,
    66: Rubber_Trans_Yellow,
    67: Rubber_Trans_Clear,
    68: Very_Light_Orange,
    69: Bright_Reddish_Lilac,
    70: Reddish_Brown,
    71: Light_Bluish_Grey,
    72: Dark_Bluish_Grey,
    73: Medium_Blue,
    74: Medium_Green,
    75: Speckle_Black_Copper,
    76: Speckle_Dark_Bluish_Grey_Silver,
    77: Light_Pink,
    78: Light_Nougat,
    79: Milky_White,
    80: Metallic_Silver,
    81: Metallic_Green,
    82: Metallic_Gold,
    83: Pearl_Black,
    84: Medium_Nougat,
    85: Medium_Lilac,
    86: Light_Brown,
    87: Metallic_Dark_Grey,
    89: Blue_Violet,
    92: Nougat,
    100: Light_Salmon,
    110: Violet,
    112: Medium_Violet,
    114: Glitter_Trans_Dark_Pink,
    115: Medium_Lime,
    117: Glitter_Trans_Clear,
    118: Aqua,
    120: Light_Lime,
    121: Light_Orange,
    123: Dark_Salmon,
    125: Spud_Orange,
    128: Dark_Nougat,
    129: Glitter_Trans_Purple,
    132: Speckle_Black_Silver,
    133: Speckle_Black_Gold,
    134: Copper,
    135: Pearl_Light_Grey,
    137: Metallic_Blue,
    142: Pearl_Light_Gold,
    147: Pearl_Dark_Gold,
    148: Pearl_Dark_Grey,
    150: Pearl_Very_Light_Grey,
    151: Very_Light_Bluish_Grey,
    158: Trans_Neon_Red,
    176: Pearl_Red,
    178: Pearl_Yellow,
    179: Pearl_Silver,
    180: Dark_Yellow,
    183: Pearl_White,
    184: Metallic_Bright_Red,
    185: Metallic_Bright_Blue,
    186: Metallic_Dark_Green,
    187: Pearl_Brown,
    189: Reddish_Gold,
    191: Bright_Light_Orange,
    200: Lemon_Metallic,
    212: Bright_Light_Blue,
    213: Medium_Blue_Violet,
    216: Rust,
    218: Reddish_Lilac,
    219: Lilac,
    220: Light_Lilac,
    225: Warm_Yellowish_Orange,
    226: Bright_Light_Yellow,
    227: Trans_Bright_Light_Green,
    231: Trans_Bright_Light_Orange,
    232: Sky_Blue,
    234: Trans_Fire_Yellow,
    256: Rubber_Black,
    272: Dark_Blue,
    273: Rubber_Blue,
    284: Trans_Reddish_Lilac,
    285: Trans_Light_Green,
    288: Dark_Green,
    293: Trans_Light_Blue_Violet,
    294: Glow_In_Dark_Trans,
    295: Flamingo_Pink,
    296: Cool_Silver,
    297: Pearl_Gold,
    300: Metallic_Copper,
    302: Glitter_Trans_Light_Blue,
    308: Dark_Brown,
    313: Maersk_Blue,
    315: Flat_Silver,
    316: Titanium_Metallic,
    320: Dark_Red,
    321: Dark_Azure,
    322: Medium_Azure,
    323: Light_Aqua,
    324: Rubber_Red,
    326: Yellowish_Green,
    329: Glow_In_Dark_White,
    330: Olive_Green,
    332: Fluorescent_Red_Ink,
    333: Fluorescent_Green_Ink,
    334: Chrome_Gold,
    335: Sand_Red,
    339: Glitter_Trans_Neon_Green,
    341: Glitter_Trans_Orange,
    342: Conductive_Black,
    346: Reddish_Copper,
    350: Rubber_Orange,
    351: Medium_Dark_Pink,
    353: Coral,
    360: Opal_Trans_Clear,
    362: Opal_Trans_Light_Blue,
    363: Opal_Trans_Black,
    364: Opal_Trans_Dark_Pink,
    365: Opal_Trans_Purple,
    366: Earth_Orange,
    367: Opal_Trans_Green,
    368: Neon_Yellow,
    370: Medium_Brown,
    371: Medium_Tan,
    373: Sand_Purple,
    375: Rubber_Light_Grey,
    376: Opal_Trans_Yellow,
    378: Sand_Green,
    379: Sand_Blue,
    383: Chrome_Silver,
    402: Reddish_Orange,
    406: Rubber_Dark_Blue,
    422: Sienna_Brown,
    423: Umber_Brown,
    424: Ochre_Yellow,
    430: Warm_Pink,
    431: Bright_Blue_Violet,
    449: Rubber_Purple,
    450: Fabuland_Brown,
    462: Medium_Orange,
    484: Dark_Orange,
    490: Rubber_Lime,
    493: Magnet,
    494: Electric_Contact_Alloy,
    495: Electric_Contact_Copper,
    496: Rubber_Light_Bluish_Grey,
    503: Very_Light_Grey,
    504: Rubber_Flat_Silver,
    507: Obsolete_Light_Orange_Brown,
    508: Fabuland_Red,
    509: Fabuland_Orange,
    510: Fabuland_Lime,
    511: Rubber_White,
    10002: Rubber_Green,
    10003: Rubber_Dark_Turquoise,
    10005: Rubber_Dark_Pink,
    10008: Rubber_Dark_Grey,
    10010: Rubber_Bright_Green,
    10015: Lemon,
    10017: Rose_Pink,
    10019: Rubber_Tan,
    10022: Yellowish_Dark_Pink,
    10026: Rubber_Magenta,
    10028: Rubber_Dark_Tan,
    10029: Rubber_Bright_Pink,
    10030: Rubber_Medium_Lavender,
    10031: Rubber_Lavender,
    10035: Rubber_Trans_Bright_Green,
    10036: Rubber_Trans_Red,
    10043: Rubber_Trans_Light_Blue,
    10045: Metallic_Light_Blue,
    10046: Metallic_Pink,
    10047: Trans_Sticker,
    10049: Metallic_Light_Pink,
    10057: Rubber_Trans_Orange,
    10070: Rubber_Reddish_Brown,
    10072: Rubber_Dark_Bluish_Grey,
    10073: Rubber_Medium_Blue,
    10078: Rubber_Light_Nougat,
    10079: Rubber_Milky_White,
    10084: Rubber_Medium_Nougat,
    10085: Rubber_Medium_Lilac,
    10092: Rubber_Nougat,
    10135: Rubber_Pearl_Light_Grey,
    10137: Rubber_Metallic_Blue,
    10147: Rubber_Pearl_Dark_Gold,
    10148: Rubber_Pearl_Dark_Grey,
    10150: Rubber_Pearl_Very_Light_Grey,
    10151: Rubber_Very_Light_Bluish_Grey,
    10189: Rubber_Reddish_Gold,
    10191: Rubber_Bright_Light_Orange,
    10200: Rubber_Lemon_Metallic,
    10212: Rubber_Bright_Light_Blue,
    10226: Rubber_Bright_Light_Yellow,
    10288: Rubber_Dark_Green,
    10297: Rubber_Pearl_Gold,
    10308: Rubber_Dark_Brown,
    10320: Rubber_Dark_Red,
    10321: Rubber_Dark_Azure,
    10322: Rubber_Medium_Azure,
    10323: Rubber_Light_Aqua,
    10326: Rubber_Yellowish_Green,
    10330: Rubber_Olive_Green,
    10351: Glitter_Trans_Bright_Green,
    10366: Opal_Trans_Dark_Blue,
    10375: Trans_Black,
    10378: Rubber_Sand_Green,
    10484: Rubber_Dark_Orange,
    11015: Trans_White,
    11019: Trans_Tan,
    20000: Canvas_Black,
    20001: Canvas_Blue,
    20002: Canvas_Green,
    20004: Canvas_Red,
    20006: Canvas_Brown,
    20007: Canvas_Light_Grey,
    20010: Canvas_Bright_Green,
    20014: Canvas_Yellow,
    20015: Canvas_White,
    20019: Canvas_Tan,
    20022: Canvas_Purple,
    20028: Canvas_Dark_Tan,
    20070: Canvas_Reddish_Brown,
    20071: Canvas_Light_Bluish_Grey,
    20072: Canvas_Dark_Bluish_Grey,
    20086: Canvas_Light_Brown,
    20288: Canvas_Dark_Green,
    20320: Canvas_Dark_Red,
    20335: Canvas_Sand_Red,
    20500: Canvas_Cream,
    30000: Modulex_Clear,
    30001: Modulex_White,
    30002: Modulex_Light_Grey,
    30003: Modulex_Black,
    30004: Modulex_Terracotta,
    30005: Modulex_Buff,
    30006: Modulex_Ochre_Yellow,
    30007: Modulex_Olive_Green,
    30008: Modulex_Teal_Blue,
    30009: Modulex_Brown,
    30010: Modulex_Strong_Red,
    30011: Modulex_Pastel_Blue,
    30012: Modulex_Orange,
    30013: Modulex_Red,
    30014: Modulex_Pastel_Green,
    30015: Modulex_Lemon,
    30016: Modulex_Pink,
    30032: Modulex_Light_Bluish_Grey,
    30033: Modulex_Pink_Red,
    30034: Modulex_Aqua_Green,
    30035: Modulex_Light_Yellow,
    30037: Modulex_Violet,
    30038: Modulex_Medium_Blue,
    30039: Modulex_Light_Orange,
    30040: Modulex_Charcoal_Grey,
    30054: Modulex_Dark_Brown,
    30080: Modulex_Foil_White,
    30081: Modulex_Foil_Black,
    30082: Modulex_Foil_Dark_Grey,
    30083: Modulex_Foil_Light_Grey,
    30084: Modulex_Foil_Dark_Green,
    30085: Modulex_Foil_Light_Green,
    30086: Modulex_Foil_Dark_Blue,
    30087: Modulex_Foil_Light_Blue,
    30088: Modulex_Foil_Violet,
    30089: Modulex_Foil_Dark_Red,
    30090: Modulex_Foil_Yellow,
    30091: Modulex_Foil_Orange,
    31000: Modulex_Dark_Grey,
    31001: Modulex_Blue,
    31002: Modulex_Very_Light_Grey,
}

ColoursByName = {
    "Black": Black,
    "Blue": Blue,
    "Green": Green,
    "Dark_Turquoise": Dark_Turquoise,
    "Red": Red,
    "Dark_Pink": Dark_Pink,
    "Brown": Brown,
    "Light_Grey": Light_Grey,
    "Dark_Grey": Dark_Grey,
    "Light_Blue": Light_Blue,
    "Bright_Green": Bright_Green,
    "Light_Turquoise": Light_Turquoise,
    "Salmon": Salmon,
    "Pink": Pink,
    "Yellow": Yellow,
    "White": White,
    "Main_Colour": Main_Colour,
    "Light_Green": Light_Green,
    "Light_Yellow": Light_Yellow,
    "Tan": Tan,
    "Light_Violet": Light_Violet,
    "Glow_In_Dark_Opaque": Glow_In_Dark_Opaque,
    "Purple": Purple,
    "Dark_Blue_Violet": Dark_Blue_Violet,
    "Edge_Colour": Edge_Colour,
    "Orange": Orange,
    "Magenta": Magenta,
    "Lime": Lime,
    "Dark_Tan": Dark_Tan,
    "Bright_Pink": Bright_Pink,
    "Medium_Lavender": Medium_Lavender,
    "Lavender": Lavender,
    "Trans_Black_IR_Lens": Trans_Black_Ir_Lens,
    "Trans_Dark_Blue": Trans_Dark_Blue,
    "Trans_Green": Trans_Green,
    "Trans_Bright_Green": Trans_Bright_Green,
    "Trans_Red": Trans_Red,
    "Trans_Dark_Pink": Trans_Dark_Pink,
    "Trans_Neon_Orange": Trans_Neon_Orange,
    "Trans_Very_Light_Blue": Trans_Very_Light_Blue,
    "Trans_Brown": Trans_Brown,
    "Trans_Medium_Blue": Trans_Medium_Blue,
    "Trans_Neon_Green": Trans_Neon_Green,
    "Trans_Light_Blue": Trans_Light_Blue,
    "Trans_Bright_Reddish_Lilac": Trans_Bright_Reddish_Lilac,
    "Trans_Pink": Trans_Pink,
    "Trans_Yellow": Trans_Yellow,
    "Trans_Clear": Trans_Clear,
    "Trans_Purple": Trans_Purple,
    "Trans_Neon_Yellow": Trans_Neon_Yellow,
    "Trans_Orange": Trans_Orange,
    "Chrome_Antique_Brass": Chrome_Antique_Brass,
    "Chrome_Blue": Chrome_Blue,
    "Chrome_Green": Chrome_Green,
    "Chrome_Pink": Chrome_Pink,
    "Chrome_Black": Chrome_Black,
    "Rubber_Yellow": Rubber_Yellow,
    "Rubber_Trans_Yellow": Rubber_Trans_Yellow,
    "Rubber_Trans_Clear": Rubber_Trans_Clear,
    "Very_Light_Orange": Very_Light_Orange,
    "Bright_Reddish_Lilac": Bright_Reddish_Lilac,
    "Reddish_Brown": Reddish_Brown,
    "Light_Bluish_Grey": Light_Bluish_Grey,
    "Dark_Bluish_Grey": Dark_Bluish_Grey,
    "Medium_Blue": Medium_Blue,
    "Medium_Green": Medium_Green,
    "Speckle_Black_Copper": Speckle_Black_Copper,
    "Speckle_Dark_Bluish_Grey_Silver": Speckle_Dark_Bluish_Grey_Silver,
    "Light_Pink": Light_Pink,
    "Light_Nougat": Light_Nougat,
    "Milky_White": Milky_White,
    "Metallic_Silver": Metallic_Silver,
    "Metallic_Green": Metallic_Green,
    "Metallic_Gold": Metallic_Gold,
    "Pearl_Black": Pearl_Black,
    "Medium_Nougat": Medium_Nougat,
    "Medium_Lilac": Medium_Lilac,
    "Light_Brown": Light_Brown,
    "Metallic_Dark_Grey": Metallic_Dark_Grey,
    "Blue_Violet": Blue_Violet,
    "Nougat": Nougat,
    "Light_Salmon": Light_Salmon,
    "Violet": Violet,
    "Medium_Violet": Medium_Violet,
    "Glitter_Trans_Dark_Pink": Glitter_Trans_Dark_Pink,
    "Medium_Lime": Medium_Lime,
    "Glitter_Trans_Clear": Glitter_Trans_Clear,
    "Aqua": Aqua,
    "Light_Lime": Light_Lime,
    "Light_Orange": Light_Orange,
    "Dark_Salmon": Dark_Salmon,
    "Spud_Orange": Spud_Orange,
    "Dark_Nougat": Dark_Nougat,
    "Glitter_Trans_Purple": Glitter_Trans_Purple,
    "Speckle_Black_Silver": Speckle_Black_Silver,
    "Speckle_Black_Gold": Speckle_Black_Gold,
    "Copper": Copper,
    "Pearl_Light_Grey": Pearl_Light_Grey,
    "Metallic_Blue": Metallic_Blue,
    "Pearl_Light_Gold": Pearl_Light_Gold,
    "Pearl_Dark_Gold": Pearl_Dark_Gold,
    "Pearl_Dark_Grey": Pearl_Dark_Grey,
    "Pearl_Very_Light_Grey": Pearl_Very_Light_Grey,
    "Very_Light_Bluish_Grey": Very_Light_Bluish_Grey,
    "Trans_Neon_Red": Trans_Neon_Red,
    "Pearl_Red": Pearl_Red,
    "Pearl_Yellow": Pearl_Yellow,
    "Pearl_Silver": Pearl_Silver,
    "Dark_Yellow": Dark_Yellow,
    "Pearl_White": Pearl_White,
    "Metallic_Bright_Red": Metallic_Bright_Red,
    "Metallic_Bright_Blue": Metallic_Bright_Blue,
    "Metallic_Dark_Green": Metallic_Dark_Green,
    "Pearl_Brown": Pearl_Brown,
    "Reddish_Gold": Reddish_Gold,
    "Bright_Light_Orange": Bright_Light_Orange,
    "Lemon_Metallic": Lemon_Metallic,
    "Bright_Light_Blue": Bright_Light_Blue,
    "Medium_Blue_Violet": Medium_Blue_Violet,
    "Rust": Rust,
    "Reddish_Lilac": Reddish_Lilac,
    "Lilac": Lilac,
    "Light_Lilac": Light_Lilac,
    "Warm_Yellowish_Orange": Warm_Yellowish_Orange,
    "Bright_Light_Yellow": Bright_Light_Yellow,
    "Trans_Bright_Light_Green": Trans_Bright_Light_Green,
    "Trans_Bright_Light_Orange": Trans_Bright_Light_Orange,
    "Sky_Blue": Sky_Blue,
    "Trans_Fire_Yellow": Trans_Fire_Yellow,
    "Rubber_Black": Rubber_Black,
    "Dark_Blue": Dark_Blue,
    "Rubber_Blue": Rubber_Blue,
    "Trans_Reddish_Lilac": Trans_Reddish_Lilac,
    "Trans_Light_Green": Trans_Light_Green,
    "Dark_Green": Dark_Green,
    "Trans_Light_Blue_Violet": Trans_Light_Blue_Violet,
    "Glow_In_Dark_Trans": Glow_In_Dark_Trans,
    "Flamingo_Pink": Flamingo_Pink,
    "Cool_Silver": Cool_Silver,
    "Pearl_Gold": Pearl_Gold,
    "Metallic_Copper": Metallic_Copper,
    "Glitter_Trans_Light_Blue": Glitter_Trans_Light_Blue,
    "Dark_Brown": Dark_Brown,
    "Maersk_Blue": Maersk_Blue,
    "Flat_Silver": Flat_Silver,
    "Titanium_Metallic": Titanium_Metallic,
    "Dark_Red": Dark_Red,
    "Dark_Azure": Dark_Azure,
    "Medium_Azure": Medium_Azure,
    "Light_Aqua": Light_Aqua,
    "Rubber_Red": Rubber_Red,
    "Yellowish_Green": Yellowish_Green,
    "Glow_In_Dark_White": Glow_In_Dark_White,
    "Olive_Green": Olive_Green,
    "Fluorescent_Red_Ink": Fluorescent_Red_Ink,
    "Fluorescent_Green_Ink": Fluorescent_Green_Ink,
    "Chrome_Gold": Chrome_Gold,
    "Sand_Red": Sand_Red,
    "Glitter_Trans_Neon_Green": Glitter_Trans_Neon_Green,
    "Glitter_Trans_Orange": Glitter_Trans_Orange,
    "Conductive_Black": Conductive_Black,
    "Reddish_Copper": Reddish_Copper,
    "Rubber_Orange": Rubber_Orange,
    "Medium_Dark_Pink": Medium_Dark_Pink,
    "Coral": Coral,
    "Opal_Trans_Clear": Opal_Trans_Clear,
    "Opal_Trans_Light_Blue": Opal_Trans_Light_Blue,
    "Opal_Trans_Black": Opal_Trans_Black,
    "Opal_Trans_Dark_Pink": Opal_Trans_Dark_Pink,
    "Opal_Trans_Purple": Opal_Trans_Purple,
    "Earth_Orange": Earth_Orange,
    "Opal_Trans_Green": Opal_Trans_Green,
    "Neon_Yellow": Neon_Yellow,
    "Medium_Brown": Medium_Brown,
    "Medium_Tan": Medium_Tan,
    "Sand_Purple": Sand_Purple,
    "Rubber_Light_Grey": Rubber_Light_Grey,
    "Opal_Trans_Yellow": Opal_Trans_Yellow,
    "Sand_Green": Sand_Green,
    "Sand_Blue": Sand_Blue,
    "Chrome_Silver": Chrome_Silver,
    "Reddish_Orange": Reddish_Orange,
    "Rubber_Dark_Blue": Rubber_Dark_Blue,
    "Sienna_Brown": Sienna_Brown,
    "Umber_Brown": Umber_Brown,
    "Ochre_Yellow": Ochre_Yellow,
    "Warm_Pink": Warm_Pink,
    "Bright_Blue_Violet": Bright_Blue_Violet,
    "Rubber_Purple": Rubber_Purple,
    "Fabuland_Brown": Fabuland_Brown,
    "Medium_Orange": Medium_Orange,
    "Dark_Orange": Dark_Orange,
    "Rubber_Lime": Rubber_Lime,
    "Magnet": Magnet,
    "Electric_Contact_Alloy": Electric_Contact_Alloy,
    "Electric_Contact_Copper": Electric_Contact_Copper,
    "Rubber_Light_Bluish_Grey": Rubber_Light_Bluish_Grey,
    "Very_Light_Grey": Very_Light_Grey,
    "Rubber_Flat_Silver": Rubber_Flat_Silver,
    "Obsolete_Light_Orange_Brown": Obsolete_Light_Orange_Brown,
    "Fabuland_Red": Fabuland_Red,
    "Fabuland_Orange": Fabuland_Orange,
    "Fabuland_Lime": Fabuland_Lime,
    "Rubber_White": Rubber_White,
    "Rubber_Green": Rubber_Green,
    "Rubber_Dark_Turquoise": Rubber_Dark_Turquoise,
    "Rubber_Dark_Pink": Rubber_Dark_Pink,
    "Rubber_Dark_Grey": Rubber_Dark_Grey,
    "Rubber_Bright_Green": Rubber_Bright_Green,
    "Lemon": Lemon,
    "Rose_Pink": Rose_Pink,
    "Rubber_Tan": Rubber_Tan,
    "Yellowish_Dark_Pink": Yellowish_Dark_Pink,
    "Rubber_Magenta": Rubber_Magenta,
    "Rubber_Dark_Tan": Rubber_Dark_Tan,
    "Rubber_Bright_Pink": Rubber_Bright_Pink,
    "Rubber_Medium_Lavender": Rubber_Medium_Lavender,
    "Rubber_Lavender": Rubber_Lavender,
    "Rubber_Trans_Bright_Green": Rubber_Trans_Bright_Green,
    "Rubber_Trans_Red": Rubber_Trans_Red,
    "Rubber_Trans_Light_Blue": Rubber_Trans_Light_Blue,
    "Metallic_Light_Blue": Metallic_Light_Blue,
    "Metallic_Pink": Metallic_Pink,
    "Trans_Sticker": Trans_Sticker,
    "Metallic_Light_Pink": Metallic_Light_Pink,
    "Rubber_Trans_Orange": Rubber_Trans_Orange,
    "Rubber_Reddish_Brown": Rubber_Reddish_Brown,
    "Rubber_Dark_Bluish_Grey": Rubber_Dark_Bluish_Grey,
    "Rubber_Medium_Blue": Rubber_Medium_Blue,
    "Rubber_Light_Nougat": Rubber_Light_Nougat,
    "Rubber_Milky_White": Rubber_Milky_White,
    "Rubber_Medium_Nougat": Rubber_Medium_Nougat,
    "Rubber_Medium_Lilac": Rubber_Medium_Lilac,
    "Rubber_Nougat": Rubber_Nougat,
    "Rubber_Pearl_Light_Grey": Rubber_Pearl_Light_Grey,
    "Rubber_Metallic_Blue": Rubber_Metallic_Blue,
    "Rubber_Pearl_Dark_Gold": Rubber_Pearl_Dark_Gold,
    "Rubber_Pearl_Dark_Grey": Rubber_Pearl_Dark_Grey,
    "Rubber_Pearl_Very_Light_Grey": Rubber_Pearl_Very_Light_Grey,
    "Rubber_Very_Light_Bluish_Grey": Rubber_Very_Light_Bluish_Grey,
    "Rubber_Reddish_Gold": Rubber_Reddish_Gold,
    "Rubber_Bright_Light_Orange": Rubber_Bright_Light_Orange,
    "Rubber_Lemon_Metallic": Rubber_Lemon_Metallic,
    "Rubber_Bright_Light_Blue": Rubber_Bright_Light_Blue,
    "Rubber_Bright_Light_Yellow": Rubber_Bright_Light_Yellow,
    "Rubber_Dark_Green": Rubber_Dark_Green,
    "Rubber_Pearl_Gold": Rubber_Pearl_Gold,
    "Rubber_Dark_Brown": Rubber_Dark_Brown,
    "Rubber_Dark_Red": Rubber_Dark_Red,
    "Rubber_Dark_Azure": Rubber_Dark_Azure,
    "Rubber_Medium_Azure": Rubber_Medium_Azure,
    "Rubber_Light_Aqua": Rubber_Light_Aqua,
    "Rubber_Yellowish_Green": Rubber_Yellowish_Green,
    "Rubber_Olive_Green": Rubber_Olive_Green,
    "Glitter_Trans_Bright_Green": Glitter_Trans_Bright_Green,
    "Opal_Trans_Dark_Blue": Opal_Trans_Dark_Blue,
    "Trans_Black": Trans_Black,
    "Rubber_Sand_Green": Rubber_Sand_Green,
    "Rubber_Dark_Orange": Rubber_Dark_Orange,
    "Trans_White": Trans_White,
    "Trans_Tan": Trans_Tan,
    "Canvas_Black": Canvas_Black,
    "Canvas_Blue": Canvas_Blue,
    "Canvas_Green": Canvas_Green,
    "Canvas_Red": Canvas_Red,
    "Canvas_Brown": Canvas_Brown,
    "Canvas_Light_Grey": Canvas_Light_Grey,
    "Canvas_Bright_Green": Canvas_Bright_Green,
    "Canvas_Yellow": Canvas_Yellow,
    "Canvas_White": Canvas_White,
    "Canvas_Tan": Canvas_Tan,
    "Canvas_Purple": Canvas_Purple,
    "Canvas_Dark_Tan": Canvas_Dark_Tan,
    "Canvas_Reddish_Brown": Canvas_Reddish_Brown,
    "Canvas_Light_Bluish_Grey": Canvas_Light_Bluish_Grey,
    "Canvas_Dark_Bluish_Grey": Canvas_Dark_Bluish_Grey,
    "Canvas_Light_Brown": Canvas_Light_Brown,
    "Canvas_Dark_Green": Canvas_Dark_Green,
    "Canvas_Dark_Red": Canvas_Dark_Red,
    "Canvas_Sand_Red": Canvas_Sand_Red,
    "Canvas_Cream": Canvas_Cream,
    "Modulex_Clear": Modulex_Clear,
    "Modulex_White": Modulex_White,
    "Modulex_Light_Grey": Modulex_Light_Grey,
    "Modulex_Black": Modulex_Black,
    "Modulex_Terracotta": Modulex_Terracotta,
    "Modulex_Buff": Modulex_Buff,
    "Modulex_Ochre_Yellow": Modulex_Ochre_Yellow,
    "Modulex_Olive_Green": Modulex_Olive_Green,
    "Modulex_Teal_Blue": Modulex_Teal_Blue,
    "Modulex_Brown": Modulex_Brown,
    "Modulex_Strong_Red": Modulex_Strong_Red,
    "Modulex_Pastel_Blue": Modulex_Pastel_Blue,
    "Modulex_Orange": Modulex_Orange,
    "Modulex_Red": Modulex_Red,
    "Modulex_Pastel_Green": Modulex_Pastel_Green,
    "Modulex_Lemon": Modulex_Lemon,
    "Modulex_Pink": Modulex_Pink,
    "Modulex_Light_Bluish_Grey": Modulex_Light_Bluish_Grey,
    "Modulex_Pink_Red": Modulex_Pink_Red,
    "Modulex_Aqua_Green": Modulex_Aqua_Green,
    "Modulex_Light_Yellow": Modulex_Light_Yellow,
    "Modulex_Violet": Modulex_Violet,
    "Modulex_Medium_Blue": Modulex_Medium_Blue,
    "Modulex_Light_Orange": Modulex_Light_Orange,
    "Modulex_Charcoal_Grey": Modulex_Charcoal_Grey,
    "Modulex_Dark_Brown": Modulex_Dark_Brown,
    "Modulex_Foil_White": Modulex_Foil_White,
    "Modulex_Foil_Black": Modulex_Foil_Black,
    "Modulex_Foil_Dark_Grey": Modulex_Foil_Dark_Grey,
    "Modulex_Foil_Light_Grey": Modulex_Foil_Light_Grey,
    "Modulex_Foil_Dark_Green": Modulex_Foil_Dark_Green,
    "Modulex_Foil_Light_Green": Modulex_Foil_Light_Green,
    "Modulex_Foil_Dark_Blue": Modulex_Foil_Dark_Blue,
    "Modulex_Foil_Light_Blue": Modulex_Foil_Light_Blue,
    "Modulex_Foil_Violet": Modulex_Foil_Violet,
    "Modulex_Foil_Dark_Red": Modulex_Foil_Dark_Red,
    "Modulex_Foil_Yellow": Modulex_Foil_Yellow,
    "Modulex_Foil_Orange": Modulex_Foil_Orange,
    "Modulex_Dark_Grey": Modulex_Dark_Grey,
    "Modulex_Blue": Modulex_Blue,
    "Modulex_Very_Light_Grey": Modulex_Very_Light_Grey,
}
